# Used to put generated files in a separate directory
targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - bin/**.dart
        options:
          build_extensions:
            '^bin/{{}}.dart': 'bin/generated/{{}}.g.dart'